config/routes.rb
Rails.application.routes.draw do

  resources :admins, only: [:index]

  # get 'participations/index'

  root "homes#top"

  
   devise_for :users, :controllers => {
     :registrations => 'users/registrations',
     :sessions => 'users/sessions'
    } 
    
  resources :users, only: [:edit, :update, :show] do
    post 'friends/accept' => 'friends#accept'
    delete 'friends/destroy_sub' => 'friends#destroy_sub'
    resources :photos
    resources :rooms
    resources :friends, only: [:index, :new, :create]
  end
  
  resources :friends, only: [:show] do
    resources :messages
  end
  
  resources :homes
  resources :posts
  resources :boards
  resources :news
  resources :voices
  resources :participations
  resources :users, only: [:index]
  resources :questions
  
  resources :inquiries do 
    resources :answers
  end
  
end

app/models/answer.rb
class Answer < ApplicationRecord
    
    validates:answer, presence:true
    
    belongs_to :inquiry
    
end

app/models/board.rb
class Board < ApplicationRecord
    mount_uploader :image, ImageUploader
    validates:title, {presence:true, length:{maximum:35}}
    validates:content, {presence:true, length:{maximum:300}}
    validates:place, {presence:true, length:{maximum:11}}
    
    belongs_to :user
    has_many :participations, :dependent => :destroy

end

app/models/friend.rb
class Friend < ApplicationRecord
    
    # belongs_to :users
    has_many :messages
end

app/models/home.rb
class Home < ApplicationRecord
    
    mount_uploader :image, ImageUploader
    
    validates:name, length:{maximum:20}
    validates:area, length:{maximum:25}
    validates:content, length:{maximum:200}
    validates:news, length:{maximum:50}
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
    
    validates:name, presence:true
    validates:email, presence:true
    validates:message, {presence:true, length:{maximum:500}}
    
    has_many :answers, :dependent => :destroy
    
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :friend
    validates:content, presence:true
end

app/models/my_user.rb
class MyUser < ApplicationRecord
end

app/models/news.rb
class News < ApplicationRecord
    validates:content, {presence:true, length:{maximum:50}}
end

app/models/participation.rb
class Participation < ApplicationRecord
    belongs_to :user
    belongs_to :board
end

app/models/photo.rb
class Photo < ApplicationRecord
    mount_uploader :image, ImageUploader
    belongs_to :user
    validates:title, length:{maximum:35}
    validates:image, presence:true
    validates:content, length:{maximum:300}
    validates:place, length:{maximum:20}
end

app/models/post.rb
class Post < ApplicationRecord
    mount_uploader :image, ImageUploader
    validates:title, {presence:true, length:{maximum:27}}
    validates:content, {presence:true, length:{maximum:180}}
    validates:place, {presence:true, length:{maximum:15}}
    
    belongs_to :user
end

app/models/question.rb
class Question < ApplicationRecord
    validates:number, presence:true
    validates:qcontent, {presence:true, length:{maximum:100}}
    validates:atext, {presence:true, length:{maximum:50}}
    validates:acontent, {presence:true, length:{maximum:300}}
end

app/models/room.rb
class Room < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    mount_uploader :icon, ImageUploader
    
    validates:name, {presence:true, length:{maximum:20}}
    validates:area, {presence:true, length:{maximum:25}}
    validates:gender, presence:true
    validates:hobby, {presence:true, length:{maximum:25}}
    validates:profile, {length:{maximum:300}}
    
    has_many :photos, :dependent => :destroy
    has_many :posts, :dependent => :destroy
    has_many :boards, :dependent => :destroy
    # has_many :friends, :dependent => :destroy
    # has_many :participations, :dependent => :destroy
    
end

app/models/voice.rb
class Voice < ApplicationRecord
    mount_uploader :image, ImageUploader
    validates:name, {presence:true, length:{maximum:35}}
    validates:age, presence:true
    validates:area, {presence:true, length:{maximum:11}}
    validates:content, {presence:true, length:{maximum:200}}
    # enum status:{nonreleased: 0, released: 1}
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
    
    def friend_check(user_id)
        
        friend_flag = nil
        
        # 現在のログインユーザーが友達リクエストをしてない、且つ友達申請が来てない状況
        if !Friend.find_by(follower_id: current_user.id, followed_id: user_id)
            if !Friend.find_by(follower_id: user_id, followed_id: current_user.id)
                friend_flag = "other"
            end
        end
        # 現在のログインユーザーが友達リクエストをしてない、且つ友達申請が来ている状況
        if Friend.find_by(follower_id: user_id, followed_id: current_user.id) &&
             !Friend.find_by(follower_id: current_user.id, followed_id: user_id)
                friend_flag = "offer"
        end   
        # 現在のログインユーザーが友達リクエストをしている、且つ友達申請が来てない状況
        if Friend.find_by(follower_id: current_user.id, followed_id: user_id)
            if !Friend.find_by(follower_id: user_id, followed_id: current_user.id)
                friend_flag = "request"
            end
        end
        # 現在のログインユーザーが友達リクエストをしている、且つ友達申請が来ている状況（つまり既に友達関係）
        if Friend.find_by(follower_id: current_user.id, followed_id: user_id)
            if Friend.find_by(follower_id: user_id, followed_id: current_user.id)
                friend_flag = "friend"
            end
        end
        
        return friend_flag
        
    end
    
end

app/views/admins/index.html.erb
<div class="admins-index">
    <div class="admins-index-title">
        <h1>管理者編集ページ一覧</h1>
    </div>
    <div class="admins-index-list">
        <ul>
            <li><%= link_to "User一覧", users_path %></li>
            <li><%= link_to "Voice一覧", voices_path %></li>
            <li><%= link_to "News一覧", news_index_path %></li>
            <li><%= link_to "Post一覧", posts_path %></li>
            <li><%= link_to "Board一覧", boards_path %></li>
            <li><%= link_to "Question一覧", questions_path %></li>
            <li><%= link_to "Inquiry一覧", inquiries_path %></li>
        </ul>
    </div>
</div>

app/views/admins/nonaccess.html.erb
<div class="error-page">
  <div class="error-main-text">
    <h1>お探しのページは存在しません。</h1>
  </div>
  <div class="error-sub-text">
    <ul>
      <li>アドレスを誤って入力したか、ページが移動した可能性があります。</li>
      <li><%= link_to "トップページに進む", "/" %></li>
    </ul>
  </div>
</div>


<style>

/*ここからスマホ用サイズ-----------------------------------------------------------------------------*/
@media(max-width:767px){

.error-page{
  padding:0;
  margin:0;
  background-color:#fff;
  text-align:center;
}

.error-main-text{
  padding:70px 0;
  margin:0;
}

.error-main-text h1{
  padding:0;
  margin:0;
  font-weight:bold;
  font-size:27px;
  color:#730E15;
}

.error-sub-text{
  padding:0;
  margin:0;
}

.error-sub-text ul{
  padding:0 0 150px 0;
  margin:0;
}

.error-sub-text li{
  padding:0;
  margin:0 0 10px 0;
  color:#000080;
  font-weight:bold;
  font-size:15px;
}

.error-sub-text a{
  padding:0;
  margin:0;
  font-size:15px;
}

.error-sub-text a:hover{
  opacity:0.5;
}


}
/*ここまでがスマホ用サイズ-----------------------------------------------------------------------------*/




/*ここからPC＆タブレット用サイズ-----------------------------------------------------------------------------*/
@media(min-width:768px){

.error-page{
  padding:0;
  margin:0;
  background-color:#fff;
  text-align:center;
}

.error-main-text{
  padding:70px 0;
  margin:0;
}

.error-main-text h1{
  padding:0;
  margin:0;
  font-weight:bold;
  font-size:30px;
  color:#730E15;
}

.error-sub-text{
  padding:0;
  margin:0;
}

.error-sub-text ul{
  padding:0 0 150px 0;
  margin:0;
}

.error-sub-text li{
  padding:0;
  margin:0 0 10px 0;
  color:#000080;
  font-weight:bold;
  font-size:20px;
}

.error-sub-text a{
  padding:0;
  margin:0;
  font-size:15px;
}

.error-sub-text a:hover{
  opacity:0.5;
}

}
/*ここまでがPC＆タブレット用サイズ-----------------------------------------------------------------------------*/

</style>