config/routes.rb
Rails.application.routes.draw do

  resources :admins, only: [:index]

  # get 'participations/index'

  root "homes#top"

  
   devise_for :users, :controllers => {
     :registrations => 'users/registrations',
     :sessions => 'users/sessions'
    } 
    
  resources :users, only: [:edit, :update, :show] do
    post 'friends/accept' => 'friends#accept'
    delete 'friends/destroy_sub' => 'friends#destroy_sub'
    resources :photos
    resources :rooms
    resources :friends, only: [:index, :new, :create]
  end
  
  resources :friends, only: [:show] do
    resources :messages
  end
  
  resources :homes
  resources :posts
  resources :boards
  resources :news
  resources :voices
  resources :participations
  resources :users, only: [:index]
  resources :questions
  
  resources :inquiries do 
    resources :answers
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    mount_uploader :icon, ImageUploader
    
    validates:name, {presence:true, length:{maximum:20}}
    validates:area, {presence:true, length:{maximum:25}}
    validates:gender, presence:true
    validates:hobby, {presence:true, length:{maximum:25}}
    validates:profile, {length:{maximum:300}}
    
    has_many :photos, :dependent => :destroy
    has_many :posts, :dependent => :destroy
    has_many :boards, :dependent => :destroy
    # has_many :friends, :dependent => :destroy
    # has_many :participations, :dependent => :destroy
    
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :gender, :hobby, :area, :icon])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    user_path(current_user.id)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    logger.debug("--------------------- login")
    super
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end
    
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    before_action :authenticate_user!
    before_action :admin_check_redirect, only: [:index]
    
    def index
        @users = User.all.order(created_at: :asc)
    end
    
    def show
        @user = User.find(params[:id])
        @boards = Board.where(user_id: @user.id).order(day: :asc)
        @posts = Post.where(user_id: @user.id).order(created_at: :desc)
        @friends = Friend.where(user_id: @user.id).order(created_at: :desc)
    end
    
    def new
        @user = User.new
    end
    
    def edit
        @user = User.find(params[:id])
        if @user.id == current_user.id
        else
            flash[:alert] = "無効なユーザー"
            redirect_to "/users/#{current_user.id}"
        end
    end
    
    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            flash[:notice] = "プロフィールを編集しました！"
            redirect_to "/users/#{@user.id}"
        else
            flash[:alert] = "入力に誤りがあります"
            redirect_to "/users/#{@user.id}/edit"
        end
    end
    
    # def destroy
    #     @user = User.find(params[:id])
    #     if @user.id == current_user.id
    #         @user.destroy
    #         # @friend.destroy
    #         flash[:notice] = "退会手続きが完了しました"
    #         redirect_to "/"
    #     else
    #         flash[:alert] = "無効なユーザー"
    #         redirect_to "/"
    #     end
    # end
    
    private
      def user_params
          params.require(:user).permit(:name, :age, :icon, :area, :gender, :profile, :hobby)
      end
    
    
    # ↓メールフォーマット-----------------------------------------------------------
    # def create
    #     @user = User.new(user_params)
    #     respond_to do |format|
    #         if @user.save
    #             shu_meeting_mail.send_when_create(@user).deliver
    #             format.html { redirect_to @user, notice: 'User was successfully created.' }
    #             format.json { render :show, status: :created, location: @user }
    #         else
    #             format.html { render :new }
    #             format.json { render json: @user.errors, status: :unprocessable_entity }
    #         end
    #     end
    # end
    
end

app/helpers/users_helper.rb
module UsersHelper
    
    def friend_check(user_id)
        
        friend_flag = nil
        
        # 現在のログインユーザーが友達リクエストをしてない、且つ友達申請が来てない状況
        if !Friend.find_by(follower_id: current_user.id, followed_id: user_id)
            if !Friend.find_by(follower_id: user_id, followed_id: current_user.id)
                friend_flag = "other"
            end
        end
        # 現在のログインユーザーが友達リクエストをしてない、且つ友達申請が来ている状況
        if Friend.find_by(follower_id: user_id, followed_id: current_user.id) &&
             !Friend.find_by(follower_id: current_user.id, followed_id: user_id)
                friend_flag = "offer"
        end   
        # 現在のログインユーザーが友達リクエストをしている、且つ友達申請が来てない状況
        if Friend.find_by(follower_id: current_user.id, followed_id: user_id)
            if !Friend.find_by(follower_id: user_id, followed_id: current_user.id)
                friend_flag = "request"
            end
        end
        # 現在のログインユーザーが友達リクエストをしている、且つ友達申請が来ている状況（つまり既に友達関係）
        if Friend.find_by(follower_id: current_user.id, followed_id: user_id)
            if Friend.find_by(follower_id: user_id, followed_id: current_user.id)
                friend_flag = "friend"
            end
        end
        
        return friend_flag
        
    end
    
end

app/views/users/destroy.html.erb
<div class="user-destroy">
    <div class="user-destroy-title">
        <p>退会内容確認ページ</p>
    </div>
    <div class="user-destroy-caution">
        <p>退会をするとあなたの情報（写真や掲示板含む）が全て削除されます。<br>
        ※復元不可</p>
    </div>
    <div class="user-destroy-main">
        <ul>
            <li><%= @user.name %></li>
            <li><%= @user.age %></li>
            <li><%= @user.gender %></li>
            <li><%= @user.area %></li>
            <li><%= @user.hobby %></li>
            <li><%= @user.profile %></li>
        </ul>
    </div>
    <div class="user-destroy-btn">
        <%= @user.submit "退会を完了させる", :class => "destroy-btn", data: {confirm: "本当に退会してもよろしいですか？"} %>
    </div>
    <div class="user-destroy-stop">
        <%= link_to "マイページに戻る", "/users/#{current_user.id}" %>
    </div>
</div>

app/views/users/edit.html.erb
<div class="user-edit">
    <div class="edit-title">
        <p>プロフィールを編集する</p>
    </div>
    <div class="edit-main">
        <%= form_for @user do |f| %>
          <p>－名前－<br>
          <span>※必須[25文字以内]</span></p>
          <%= f.text_field :name, :class => "user-edit-content1" %>
          <p>－年齢－</p>
          <%= f.number_field :age, :class => "user-edit-content1" %>
          <p>－活動エリア－<br>
          <span>※必須[25文字以内]</span></p>
          <%= f.text_field :area, :class => "user-edit-content1" %>
          <p>－性別－<br>
          <span>※必須</span></p>
          <%= f.radio_button :gender, :"女性" %>
          <%= f.label :gender, "女性", :class => "gender" %>
          <%= f.radio_button :gender, :"男性" %>
          <%= f.label :gender, "男性", :class => "gender" %>
          <%= f.radio_button :gender, :"その他" %>
          <%= f.label :gender, "その他" %>
          <p>－趣味－<br>
          <span>※必須[25文字以内]</span></p>
          <%= f.text_field :hobby, :class => "user-edit-content1" %>
          <p>－自己紹介－<br>
          <span>※150文字以内</span></p>
          <%= f.text_area :profile, :size=>"20x7", :class => "user-edit-content2" %>
          <p>－アイコン－</p>
          <%= f.file_field :icon, :class => "user-edit-content3" %>
          <br>
          <ul>
              <li><a class="user-edit-btn2" href="/users/<%= current_user.id %>">マイページに戻る</a></li>
              <li><%= f.submit "反映する", :class => "user-edit-btn1", data: {confirm: '内容を変更してもよろしいでしょうか？'} %></li>
          </ul>
        <% end %>
    </div>
</div>

app/views/users/index.html.erb
<div class="users-index">
    
    <div class="users-index-title">
        <p>ユーザー一覧<br>
        ※アプリ管理者のみ編集可能</p>
    </div>
    
    <% @users.each do |u| %>
      <div class="users-index-main clearfix">
        <div class="users-index-image clearfix">
          <% if u.icon.present? %>
            <%= image_tag u.icon, :class => "users-img" %>
          <% else %>
            <%= image_tag "default-post.jpg", :class => "users-img" %>
          <% end %>
        </div>
        <div class="users-index-detail clearfix">
            <ul>
                <li>ユーザー名：<%= link_to u.name, "/users/#{u.id}" %></li>
                <li>性別：<%= u.gender %></li>
                <li>年齢：<%= u.age %></li>
                <li>主な趣味：<%= u.hobby %></li>
                <li>主な活動場所：<%= u.area %></li>
                <li>登録日時：<%= u.created_at.strftime("%Y/%m/%d %H:%M") %></li>
                <li>更新日時：<%= u.updated_at.strftime("%Y/%m/%d %H:%M") %></li>
            </ul>
        </div>
      </div>
    <% end %>
    
</div>

app/views/users/show.html.erb
<div class="user-page">
    <div class="user-title">
        <p><%= @user.name %>さんのページ</p>
    </div>
    <div class="user-icon">
        <% if @user.icon.present? %>
            <p><%= image_tag @user.icon, :class => "icon-size" %></p>
        <% else %>
            <p><%= image_tag "default-icon.jpg", :class => "icon-size" %></p>
        <% end %>
    </div>
    <div class="user-page-friends-btn">
        <% if @user.id != current_user.id %>
        <ul>
            <% if friend_check(@user.id) == "other" %>
              <li><%= link_to "友達申請する", "/users/#{@user.id}/friends", method: "post" %></li>
            <% elsif friend_check(@user.id) == "request" %>
              <li><%= link_to "友達申請中", "/users/#{current_user.id}/friends/#{@user.id}", method: "delete", data: {confirm: '友達申請をやめますか？'} %></li>
            <% elsif friend_check(@user.id) == "offer" %>
              <li><%= link_to "承認する", " /users/#{@user.id}/friends/accept", method: "post", data: {confirm: '承認しますか？'} %></li>
            <% elsif friend_check(@user.id) == "friend" %>
              <li><%= link_to "友達", "/users/#{@user.id}/friends/destroy_sub", method: "delete", data: {confirm: '友達を解除しますか？※ボタンが「承認待ち」に切り替わります。'} %></li>
              <li><%= link_to "チャットをする", "/friends/#{Friend.find_by(follower_id: current_user.id, followed_id: @user.id).id}/messages" %></li>
              <!--↑フォローしている側のidが現在ログインしているユーザーのidで、フォローされている側のidが友達になっているユーザーのid-->
            <% end %>                         
        </ul>
        <% end %>
    </div>
    <div class="user-page-header">
        <ul>
            <li><%= link_to "友達一覧", "/users/#{@user.id}/friends" %></li>
            <li><%= link_to "アルバム", user_photos_path(@user.id) %></li>
            <li><%= link_to "掲示板一覧", "#user-boards-index" %></li>
            <li><%= link_to "投稿一覧", "#user-posts-index" %></li>
        </ul>
    </div>
    <div class="user-page-main">
        <p><span>活動場所</span><%= @user.area %></p>
        <p><span>主な趣味</span><%= @user.hobby %></p>
        <p><span>性別</span><%= @user.gender %></p>
        <p><span>年齢</span><%= @user.age %>歳</p>
        <h3>－自己紹介―</h3><br>
        <%= simple_format(@user.profile) %>
        
        <% if @user.id == current_user.id %>
          <div class="user-page-edit">
              <ul>
                  <li><%= link_to "プロフィールを編集する", "/users/#{current_user.id}/edit" %></li>
              </ul>
          </div>
        <% end %>
    </div>
    
    
    
<!--[掲示板表示]-->
<div id="user-boards-index" style="height: 100px;"></div>


<div class="user-page-boards">
    <div class="user-page-boards-new">
        <p><%= link_to "掲示板を新規作成する", "/boards/new" %></p>
    </div>
    <div class="user-boards-title">
        <h3>掲示板一覧</h3>
    </div>
    
    <% @boards.each do |b| %>
      <div class="user-boards-main">
          <div class="user-boards-main-title">
              <p><%= b.title %></p>
          </div>
          <div class="user-boards-main-content clearfix">
              <div class="user-boards-main-text">
                  <ul>
                      <li>開催日：<span><%= b.day.strftime("%Y/%m/%d") %></span></li>
                      <li>開催時間：<span><%= b.times.strftime("%H:%M") %></span></li>
                      <li>場所：<span><%= b.place %></span></li>
                      <li>主催者：<span><%= @user.name %></span></li>
                  </ul>
                  <div class="user-boards-btn">
                      <%= link_to "詳細を見る", "/boards/#{b.id}" %>
                  </div>
              </div>
              <div class="user-boards-main-image">
                <% if b.image.present? %>
                  <%= image_tag b.image, class: "user-boards-img" %>
                <% else %>
                  <%= image_tag "default-board.jpg", :class => "user-boards-img" %>
                <% end %>
              </div>
          </div>
      </div>
    <% end %>
</div>
    
    
<!--[投稿表示]-->
    <div id="user-posts-index" style="height: 100px;"></div>

    <div class="user-page-posts">
        <div class="user-page-posts-new">
            <p><%= link_to "投稿を新規作成する", "/posts/new" %></p>
        </div>
        <div class="user-posts-title">
            <h3>投稿一覧</h3>
        </div>
        <% @posts.each do |p| %>
            <div class="user-posts-main">
                <div class="user-posts-title">
                    <ul>
                        <li><%= p.title %></li>
                        <li>＠<%= p.place %></li>
                    </ul>
                </div>
                <div class="user-posts-content clearfix">
                    <div class="user-posts-detail">
                            <p><%= p.content %><br>
                    </div>
                    <div class="user-posts-image">
                        <% if p.image.present? %>
                          <p><%= image_tag p.image, class: "posts-img" %></p>
                        <% else %>
                          <p><%= image_tag "default-post.jpg", :class => "posts-img" %></p>
                        <% end %>
                    </div>
                </div>
                <div class="user-posts-times">
                    <ul>
                        <li>投稿日時：<%= p.created_at.strftime("%Y/%m/%d %H:%M") %></li>
                        ／<li>更新日時：<%= p.updated_at.strftime("%Y/%m/%d %H:%M") %></li>
                    </ul>
                </div>
                <div class="posts-btn clearfix">
                    <% if p.user_id == current_user.id or current_user.id == 0 %>
                      <ul>
                          <li><%= link_to "削除する", "/posts/#{p.id}", method: "delete", data: {confirm: '本当に削除してもよろしいでしょうか？'} %></li>
                          <% if p.user_id == current_user.id %>
                            <li><%= link_to "編集する", edit_post_path(p.id) %></li>
                          <% end %>
                      </ul>
                   <% end %>
                </div>
            </div>
       <% end %>
    </div>
</div>